# Generated by Django 4.1.2 on 2022-12-09 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messeges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='to_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='from_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
