# Generated by Django 4.1.2 on 2022-12-10 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messeges', '0002_message_to_id_alter_message_from_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date_time',
        ),
        migrations.AddField(
            model_name='message',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
