# Generated by Django 4.1.2 on 2022-12-14 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messeges', '0003_remove_message_date_time_message_data_dodania'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='friend1', to=settings.AUTH_USER_MODEL)),
                ('friend2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='friend2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
